[project]
name = "nextbikeosm"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "diskcache>=5.6.3",
    "jinja2>=3.1.6",
    "overpy>=0.7",
    "python-slugify>=8.0.4",
    "starsep-utils>=0.8.0",
]
